# To connect to ec2 instance, first give permission to your key. Run ...
chmod 400 private-server-devops-key.pem

# And finally to connect, use ...
ssh -i "private-server-devops-key.pem" ubuntu@10.0.2.74
